// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwinkqdcxxwnommdjxsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3aW5rcWRjeHh3bm9tbWRqeHNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMTU0MjUsImV4cCI6MjA2NjU5MTQyNX0.QAaDH0uxTwyS_BuhG0Nllx2tSoIKP31SCBeFNdlfHsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);